public class TwilioApplication {

	public String sid { get; set; }
	public String date_created { get; set; }
	public String date_updated { get; set; }
	public String account_sid { get; set; }
	public String api_version  { get; set; }
	public String voice_url  { get; set; }
	public String voice_method  { get; set; }
	public String voice_fallback_url  { get; set; }
	public String voice_fallback_method  { get; set; }
	public String status_callback  { get; set; }
	public String status_callback_method  { get; set; }
	public String voice_caller_id_lookup  { get; set; }
	public String sms_url  { get; set; }
	public String sms_method  { get; set; }
	public String sms_fallback_url  { get; set; }
	public String sms_fallback_method  { get; set; }
	public String sms_status_callback  { get; set; }
	public String uri  { get; set; }

}