public class TwilioSMS {
 	public String sid { get; set; }
    public String date_sent { get; set;}
    public String account_sid { get; set;}
    public String to { get; set;}
    public String body { get; set;}
    public String frm { get; set;}
    public String direction { get; set;}
    public String status { get; set;}
    public String price { get; set;}
    public String api_version { get; set;}
    public String date_created { get; set; }
    public String date_updated { get; set; }
    public String uri { get; set; }
        
    public TwilioSMS() {
    }
}